"""Master module-enable switches and other on/off feature flags.

Every value below is now sourced from :mod:`quake_loyola.config` (defaults
hardcoded there, optionally overridden by ``ql.toml`` at the repo root — see
that module's docstring, or run ``ql conf show``). The comments here
describe what each flag does; the *value* itself lives in
``config.DEFAULTS`` and is only overridden when the user sets it via
``ql conf set <NAME> <value>``.
"""

from ..config import get as _flag

# ════════════════════════════════════════════════════════════════════════════════
# MASTER MODULE SWITCHES — flip a flag to True (via `ql conf set NAME true`,
# or by editing ql.toml) to re-enable that module's geometry. Module masters
# (BRIDGE_ENABLED, WEST_CAMPUS_ENABLED, KNOTT_ENABLED, ENTITIES_ENABLED,
# MARYLAND_ENABLED, LIGHTS_ENABLED) default to False so only the world-shell
# rectangle (streets.py, which is never gated — it seals the level) is
# generated by default; per-section sub-flags nested under an off-by-default
# master (e.g. BRIDGE_ENABLED_SPAN_CENTER, WEST_CAMPUS_ENABLED_FENCE) may
# themselves default to True so that flipping just the module master on
# reveals a fully-detailed module rather than an empty shell. See
# config.DEFAULTS for the authoritative per-flag default.
# ════════════════════════════════════════════════════════════════════════════════
BRIDGE_ENABLED = _flag(
    "BRIDGE_ENABLED"
)  # convenience master: if True, forces every BRIDGE_ENABLED_<section> flag below on, overriding their individual settings. Leave False and flip the per-section flags to review one span at a time.
BRIDGE_ENABLED_SPAN_WEST_APPROACH = _flag(
    "BRIDGE_ENABLED_SPAN_WEST_APPROACH"
)  # bridge.py span: Pier 1 (west abutment) .. Pier 2
BRIDGE_ENABLED_SPAN_CENTER = _flag(
    "BRIDGE_ENABLED_SPAN_CENTER"
)  # bridge.py span: Pier 2 .. Pier 3 (curved arch span over Charles St)
BRIDGE_ENABLED_SPAN_EAST_APPROACH = _flag(
    "BRIDGE_ENABLED_SPAN_EAST_APPROACH"
)  # bridge.py span: Pier 3 .. Pier 4 (west KH pier)
BRIDGE_ENABLED_SPAN_KH = _flag(
    "BRIDGE_ENABLED_SPAN_KH"
)  # bridge.py span: Pier 4 .. Pier 5 (east KH pier / NE pier)
BRIDGE_ENABLED_SPAN_EAST_EXT = _flag(
    "BRIDGE_ENABLED_SPAN_EAST_EXT"
)  # bridge.py span: Pier 5 .. Pier 6 (extended east section to Ennis Rd)
STREETS_ENABLED_DETAILS = _flag(
    "STREETS_ENABLED_DETAILS"
)  # streets.py content other than the world-shell rectangle (roads, sidewalks, curbs, lamps, trees, driveways, Ennis entrance features)
WEST_CAMPUS_ENABLED = _flag(
    "WEST_CAMPUS_ENABLED"
)  # convenience master: if True, forces WEST_CAMPUS_ENABLED_DORMS, WEST_CAMPUS_ENABLED_FENCE, WEST_CAMPUS_ENABLED_TERRAIN, WEST_CAMPUS_ENABLED_WALL, and WEST_CAMPUS_ENABLED_SIDEWALK all on, overriding their individual settings. Leave False and flip the per-section flags to review one piece at a time (same pattern as BRIDGE_ENABLED).
WEST_CAMPUS_ENABLED_DORMS = _flag(
    "WEST_CAMPUS_ENABLED_DORMS"
)  # west_campus.py — dorm buildings and grounds
WEST_CAMPUS_ENABLED_FENCE = _flag(
    "WEST_CAMPUS_ENABLED_FENCE"
)  # west_campus.py — iron fence along the east
# face of the (currently disabled) west-campus buildings. Kept independent of
# WEST_CAMPUS_ENABLED_DORMS so the fence can be shown along Charles St even
# while the dorm buildings themselves stay off.
WEST_CAMPUS_ENABLED_TERRAIN = _flag(
    "WEST_CAMPUS_ENABLED_TERRAIN"
)  # west_campus_terrain.py — real-elevation
# ground fill under/around the dorm buildings + bridge west approach. Kept
# independent of WEST_CAMPUS_ENABLED_DORMS (same reasoning as
# KNOTT_ENABLED_TERRAIN vs KNOTT_ENABLED) so the terrain can be reviewed on
# its own even while the buildings themselves stay off.
WEST_CAMPUS_ENABLED_WALL = _flag(
    "WEST_CAMPUS_ENABLED_WALL"
)  # west_campus.py — brick wall with gate, pillars,
# and iron fence south of bridge Pier 1 (DORM_PIER_X), running from the north
# face of dorm 2 up to the pier. Kept independent of WEST_CAMPUS_ENABLED_DORMS
# so the wall reads as a bridge-approach feature even while the dorm
# buildings themselves stay off.
WEST_CAMPUS_ENABLED_SIDEWALK = _flag(
    "WEST_CAMPUS_ENABLED_SIDEWALK"
)  # west_campus.py — flush stone walkway
# in front of the dorms, with a spur running north to the brick-wall door.
# Kept independent of WEST_CAMPUS_ENABLED_DORMS (same reasoning as
# WEST_CAMPUS_ENABLED_WALL) so the walkway/spur can be shown even while the
# dorm buildings themselves stay off.
NE_ENABLED_TERRAIN = _flag(
    "NE_ENABLED_TERRAIN"
)  # ne_terrain.py — real-elevation ground fill for the
# NE quadrant (north of Ennis Road, east of Charles St), replacing the flat
# placeholder box streets.py used to build there. See ne_terrain.py's module
# docstring for the real-elevation-derived design and the two flush ties
# (Charles St east sidewalk to the west, Ennis Road north curb to the south).
KNOTT_ENABLED_TERRAIN = _flag(
    "KNOTT_ENABLED_TERRAIN"
)  # knott_terrain.py — KH surrounding terrain/embankment/driveway
KNOTT_ENABLED = _flag(
    "KNOTT_ENABLED"
)  # knott_hall.py — KH building shell (walls, windows, roof, sign)
ENTITIES_ENABLED = _flag(
    "ENTITIES_ENABLED"
)  # entities.py — items, monsters, decorative lights, extra spawns (a single info_player_start is always kept so the map stays loadable)
# Per-group sub-flags nested under ENTITIES_ENABLED (only take effect when
# that master is True) — mirrors the BRIDGE_ENABLED_SPAN_*/WEST_CAMPUS_ENABLED_*
# pattern so each entity group can be toggled independently while testing.
ENTITIES_ENABLED_TELEPORTS = _flag(
    "ENTITIES_ENABLED_TELEPORTS"
)  # bridge west/east arch + Charles St arches + Ennis/KH-driveway arch teleports
ENTITIES_ENABLED_DM_SPAWNS = _flag(
    "ENTITIES_ENABLED_DM_SPAWNS"
)  # info_player_deathmatch spawns
ENTITIES_ENABLED_WEAPONS = _flag("ENTITIES_ENABLED_WEAPONS")  # weapon_* pickups
ENTITIES_ENABLED_AMMO = _flag("ENTITIES_ENABLED_AMMO")  # item_rockets/shells/spikes
ENTITIES_ENABLED_HEALTH = _flag("ENTITIES_ENABLED_HEALTH")  # item_health/armor pickups
ENTITIES_ENABLED_MONSTERS = _flag(
    "ENTITIES_ENABLED_MONSTERS"
)  # non-KH-interior monsters (ogres, grunts, demon knights); KH-interior
# monsters remain separately gated by KNOTT_ENABLED_MONSTERS
ENTITIES_ENABLED_VEGETATION = _flag(
    "ENTITIES_ENABLED_VEGETATION"
)  # decorative trees/bushes
ENTITIES_ENABLED_PLATFORM = _flag(
    "ENTITIES_ENABLED_PLATFORM"
)  # Charles St scrolling platform loop + its rocket launchers
ENTITIES_ENABLED_EXIT = _flag(
    "ENTITIES_ENABLED_EXIT"
)  # single-player trigger_changelevel exit portal
LIGHTS_ENABLED = _flag(
    "LIGHTS_ENABLED"
)  # master switch for every "light"-classname entity across all modules (streets, entities, west_campus, bridge, etc.); see generate_map.py filter
LIGHTS_ENABLED_TORCHES = _flag(
    "LIGHTS_ENABLED_TORCHES"
)  # light "group" flag: torch/flame fixtures only
LIGHTS_ENABLED_DECK_WALL = _flag(
    "LIGHTS_ENABLED_DECK_WALL"
)  # light "group" flag: bridge.py parapet-block base wall lights only — on by
# default (unlike LIGHTS_ENABLED_TORCHES) since they're a small, low-impact
# decorative detail meant to always show, independent of the LIGHTS_ENABLED master.
BASEMENT_ENABLED_LIGHTS = _flag(
    "BASEMENT_ENABLED_LIGHTS"
)  # light "group" flag: basement.py fixtures only —
# on by default (unlike LIGHTS_ENABLED_TORCHES's pattern above, kept True since
# the basement is otherwise a fully unlit sky-textured void with no ambient
# light source, and would render as solid black without at least a few
# lights placed inside it).
# (bridge pillar tops, Ennis entrance pillars, Ennis cement-wall lamppost,
# campus lamp posts) — same convenience-master pattern as BRIDGE_ENABLED:
# LIGHTS_ENABLED=True forces every light group on (including this one),
# overriding the individual setting; leave LIGHTS_ENABLED False and flip
# this (or future per-group flags) to review one light group at a time.
# See generate_map.py filter — torch entities carry an internal
# "_light_group" field so they can be told apart from other "light"-
# classname entities (pendant lights, pillar uplights, etc.) that aren't
# part of any group yet and stay off until LIGHTS_ENABLED is True.
MARYLAND_ENABLED = _flag(
    "MARYLAND_ENABLED"
)  # maryland_hall.py — placeholder Maryland Hall massing block, east of Ennis Parallel
MARYLAND_ENABLED_TERRAIN = _flag(
    "MARYLAND_ENABLED_TERRAIN"
)  # maryland_terrain.py — ground mound under/around the Maryland Hall stub
# Kept independent of KNOTT_ENABLED_TERRAIN so each hill/mound can be flipped
# on and off separately while both are still placeholder/provisional models.

BRIDGE_ENABLED_FASCIA_TEXT = _flag("BRIDGE_ENABLED_FASCIA_TEXT")

BRIDGE_ENABLED_SUPPORTS = _flag("BRIDGE_ENABLED_SUPPORTS")
