"""Voxel tree profiles used by geometry.make_pixel_tree()."""

# Characters: L = leaf, B = branch, T = trunk, space = empty.
TREE_PROFILES: dict[str, list[str]] = {
    # Narrow columnar street tree.
    "street": [
        "  LLL  ",
        " LLLLL ",
        "LLLLLLL",
        " LLLLL ",
        "  LLL  ",
        "  BBB  ",
        "  TTT  ",
        "  TTT  ",
        "  TTT  ",
        "  TTT  ",
    ],
    # Broad-crowned deciduous tree.
    "deciduous": [
        "   LLL   ",
        "  LLLLL  ",
        " LLLLLLL ",
        "LLLLLLLLL",
        " LLLLLLL ",
        "  LLLLL  ",
        "   LBL   ",
        "   TTT   ",
        "   TTT   ",
        "   TTT   ",
        "   TTT   ",
        "   TTT   ",
    ],
    # Conifer.
    "pine": [
        "    L    ",
        "   LLL   ",
        "  LLLLL  ",
        " LLLLLLL ",
        "  LLLLL  ",
        " LLLLLLL ",
        "LLLLLLLLL",
        "   BBB   ",
        "   TTT   ",
        "   TTT   ",
        "   TTT   ",
        "   TTT   ",
    ],
    # Large broad-crown tree profile for vox_size=8.
    "large": [
        "            LL            ",
        "          LLLLLL          ",
        "        LLLLLLLLLL        ",
        "      LLLLLLLLLLLLLL      ",
        "    LLLLLLLLLLLLLLLLLL    ",
        "   LLLLLLLLLLLLLLLLLLLL   ",
        "  LLLLLLLLLLLLLLLLLLLLLL  ",
        " LLLLLLLLLLLLLLLLLLLLLLLL ",
        "LLLLLLLLLLLLLLLLLLLLLLLLL ",
        "LLLLLLLLLLLLLLLLLLLLLLLLLL",
        "LLLLLLLLLLLLLLLLLLLLLLLLLL",
        " LLLLLLLLLLLLLLLLLLLLLLLL ",
        "  LLLLLLLLLLLLLLLLLLLLLL  ",
        "   LLLLLLLLLLLLLLLLLLLL   ",
        "  LLLLLLLLLLLLLLLLLLLLLL  ",
        " LLLLLLLLLLLLLLLLLLLLLLLL ",
        "LLLLLLLLLLLLLLLLLLLLLLLLLL",
        " LLLLLLLLLLLLLLLLLLLLLLL  ",
        "  LLLLLLLLLLLLLLLLLLLLLL  ",
        "   LLLLLLLLLLLLLLLLLLLL   ",
        "    LLLLLLLLLLLLLLLLLL    ",
        "   LLLLLLLLLLLLLLLLLLLL   ",
        "    LLLLLLLLLLLLLLLLLL    ",
        "      LLLLLLLLLLLLLL      ",
        "       LLLLLLLLLLLL       ",
        "        LLLLLLLLL         ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
        "           TTTT           ",
    ],
}
